@api = http://localhost:5298

### add category
Post {{api}}/api/category
Content-Type: application/json

{
    "name": "Napoje"
}

### get categories
Get {{api}}/api/categories
Content-Type: application/json

{
}

### get categoryId
Get {{api}}/api/category/{65f57fb8-740b-4ad5-871c-8bc850f377a4}
Content-Type: application/json

{
}