@api = http://localhost:5298

### add category
Post {{api}}/category
Content-Type: application/json

{
    "name": "Napoje"
}

### get categories
Get {{api}}/categories
Content-Type: application/json

{
}